payum:
    storages:
        App\Entity\Payment\Payment:
            doctrine: orm
    security:
        token_storage:
            App\Entity\Payment\PaymentToken:
                doctrine: orm
    gateways:
        offline:
            factory: offline
        paypal:
            factory: paypal
            username:  'rkota_api1.nsat.africa'
            password:  'Z5R3Z4KLK7TVL54G'
            signature: 'A6Acs5FR3vMOfBMu3-nX9RducZb.AW2NAg9adLBgxcUpx7P1bv3xj-u2'
            sandbox: true

