#security_logout:
   #path: /logout
#    controller: App\Controller\DefaultController::index
#app_logout:
    #path: /logout
    #methods: GET
# checkout_payment_paypal:
#   path: /checkout/payment/paypal
#   controller: App\Controller\checkout\PaymentController::index